### ISSUE TITLE
希望大佬添加这个功能，命令构建planet和moon

### ISSUE THREAD

**Issue by MINGERTAI** [niliovo/zerotier-aio-zh#2]
```
# 构建 moon
docker exec -it zerotier-planet build moon
# 构建 planet
docker exec -it zerotier-planet build planet
# 查询客户端配置moon方法
docker exec -it zerotier-planet build moonid
```
这样在设置AUTOGEN_PLANET=0时还可以返悔，生成planet文件与moon文件

**Comment by niliovo** [comment]
如果映射了 `/your_path/zerotier-aio-zh/etc/zt-mkworld:/etc/zt-mkworld` 目录，仅需要删除此目录下 `ALREADY_INITED` 空文件后，删除并重新启动容器即可再次创建, `AUTOGEN_PLANET`参数逻辑为检测`ALREADY_INITED` 空文件，如果已存在此文件则不进行操作
